# Name of the site, displayed in the navigation

site_name: sda-dropwizard-commons

# To display a page inside the navigation you must include them here

# These files are relative to the /docs repository

# Learn more on <https://www.mkdocs.org/user-guide/writing-your-docs/>

nav:
  - Overview: index.md
  - Metadata Context: metadata-context.md
  - Modules:
    - Bom: bom.md
    - Client Jersey: client-jersey.md
    - Client Jersey Example: client-jersey-example.md
    - Client Jersey Wiremock Testing: client-jersey-wiremock-testing.md
    - Dependencies: dependencies.md
    - Metadata Context: metadata-context.md
    - Server Auth: server-auth.md
    - Server Auth Testing: server-auth-testing.md
    - Server Circuit Breaker: server-circuit-breaker.md
    - Server Cloud Events: server-cloud-events.md
    - Server Consumer: server-consumer.md
    - Server Cors: server-cors.md
    - Server Dropwizard: server-dropwizard.md
    - Server Error Handling: server-error-handling.md
    - Server Healthcheck: server-healthcheck.md
    - Server Healthcheck Example: server-healthcheck-example.md
    - Server Hibernate: server-hibernate.md
    - Server Hibernate Example: server-hibernate-example.md
    - Server Hibernate Testing: server-hibernate-testing.md
    - Server Jackson: server-jackson.md
    - Server Kafka: server-kafka.md
    - Server Kafka Example: server-kafka-example.md
    - Server Kafka Testing: server-kafka-testing.md
    - Server Key Management: server-key-mgmt.md
    - Server Mongo Testing: server-mongo-testing.md
    - Server OpenApi: server-open-api.md
    - Server OpenApi Example: server-openapi-example.md
    - Server Open Telemetry: server-opentelemetry.md
    - Server Open Telemetry Example: server-opentelemetry-example.md
    - Server Prometheus: server-prometheus.md
    - Server S3: server-s3.md
    - Server S3 Testing: server-s3-testing.md
    - Server Security: server-security.md
    - Server Spring Data Mongo: server-spring-data-mongo.md
    - Server Testing: server-testing.md
    - Server Trace: server-trace.md
    - Server Weld: server-weld.md
    - Server Weld Example: server-weld-example.md
    - Server Weld Testing: server-weld-testing.md
    - Shared Async API: shared-asyncapi.md
    - Shared Certificates: shared-certificates.md
    - Shared Error: shared-error.md
    - Shared Forms: shared-forms.md
    - Shared Tracing: shared-tracing.md
    - Shared Yaml: shared-yaml.md
    - Starter: starter.md
    - Starter Example: starter-example.md
  - Migration Guides:
    - Migrate from v2 to v3: migration-guides/MIGRATION_GUIDE_v2_to_v3.md
    - Migrate from v5 to v6: migration-guides/MIGRATION_GUIDE_v5_to_v6.md
    - Migrate from v8 to v9: migration-guides/MIGRATION_GUIDE_v8_to_v9.md

# Always include the techdocs-core plugin, otherwise it's not possible to
# display the documentation in Backstage. We don't support other plugins

plugins:
  - techdocs-core

markdown_extensions:
  # Add support for the `--8<--` feature to import files. Remove this as soon as it is
  # part of the techdocs-core plugin: https://github.com/backstage/mkdocs-techdocs-core/issues/20
  - pymdownx.snippets
