name: Maven Dependency Resolution

on: [pull_request]

env:
  SEMANTIC_VERSION: local-SNAPSHOT

jobs:
  maven-dependency-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Publish jars locally
        run: ./gradlew publishToMavenLocal

      # This test is a simplified version of the dependency check performed by Maven Central on
      # release. As dependency resolution is different between Gradle and Maven, in some cases
      # everything is fine in Gradle and in dependent Gradle projects, although some dependency
      # versions can't be resolved in a Maven project and also fail the validation when releasing
      # to Maven Central.
      - name: Verify dependency resolution with Maven
        working-directory: .github/mvn-verification
        run: mvn dependency:list | tee /dev/stderr | grep '\[ERROR]' && exit 1 || exit 0
